export const patientAppointments = [
  {
    a_id: 1,
    patient: 101,
    doctor_name: "Dr. Rajesh Kumar",
    doctor_number: 1234567890,
    specialization: "Cardiologist",
    rating: 4.8,
    hospital_name: "AIIMS Delhi",
    hospital_number: 9876543210,
    hospital_address: "Ansari Nagar, New Delhi, India",
    description: "Regular Checkup",
    time: "2023-09-20T10:00:00.000Z",
    is_emergency: 0,
    status: -1,
    prescription: null,
  },
  {
    a_id: 2,
    patient: 102,
    doctor_name: "Dr. Priya Sharma",
    doctor_number: 9876543210,
    specialization: "Dermatologist",
    rating: 4.5,
    hospital_name: "Fortis Hospital Mumbai",
    hospital_number: 1234567890,
    hospital_address: "Mulund West, Mumbai, India",
    description: "Skin Check",
    time: "2023-09-21T14:30:00.000Z",
    is_emergency: 0,
    status: -1,
    prescription: null,
  },
  {
    a_id: 3,
    patient: 103,
    doctor_name: "Dr. Suresh Patel",
    doctor_number: 5555555555,
    specialization: "Orthopedic Surgeon",
    rating: 4.9,
    hospital_name: "Apollo Hospital Chennai",
    hospital_number: 9876543210,
    hospital_address: "Greams Road, Chennai, India",
    description: "Knee Pain Consultation",
    time: "2023-09-22T11:15:00.000Z",
    is_emergency: 0,
    status: 0,
    prescription: null,
  },
  {
    a_id: 4,
    patient: 104,
    doctor_name: "Dr. Nandini Gupta",
    doctor_number: 1234567890,
    specialization: "Gynecologist",
    rating: 4.7,
    hospital_name: "Max Hospital Delhi",
    hospital_number: 9876543210,
    hospital_address: "Saket, New Delhi, India",
    description: "Prenatal Checkup",
    time: "2023-09-23T09:45:00.000Z",
    is_emergency: 0,
    status: -1,
    prescription: null,
  },
  {
    a_id: 5,
    patient: 105,
    doctor_name: "Dr. Anand Verma",
    doctor_number: 9876543210,
    specialization: "Neurologist",
    rating: 4.6,
    hospital_name: "NIMHANS Bangalore",
    hospital_number: 1234567890,
    hospital_address: "Hosur Road, Bangalore, India",
    description: "Headache Consultation",
    time: "2023-09-24T15:30:00.000Z",
    is_emergency: 0,
    status: -1,
    prescription: null,
  },
  {
    a_id: 6,
    patient: 106,
    doctor_name: "Dr. Meera Reddy",
    doctor_number: 5555555555,
    specialization: "Pediatrician",
    rating: 4.8,
    hospital_name: "Rainbow Children's Hospital Hyderabad",
    hospital_number: 9876543210,
    hospital_address: "Banjara Hills, Hyderabad, India",
    description: "Child Vaccination",
    time: "2023-09-25T13:00:00.000Z",
    is_emergency: 0,
    status: -1,
    prescription: null,
  },
  {
    a_id: 7,
    patient: 107,
    doctor_name: "Dr. Arjun Singh",
    doctor_number: 1234567890,
    specialization: "Ophthalmologist",
    rating: 4.9,
    hospital_name: "Shankar Netralaya Chennai",
    hospital_number: 9876543210,
    hospital_address: "Radhakrishnan Salai, Chennai, India",
    description: "Eye Checkup",
    time: "2023-09-26T10:30:00.000Z",
    is_emergency: 0,
    status: -1,
    prescription: null,
  },
  {
    a_id: 8,
    patient: 108,
    doctor_name: "Dr. Aarti Gupta",
    doctor_number: 9876543210,
    specialization: "ENT Specialist",
    rating: 4.6,
    hospital_name: "Apollo Hospital Mumbai",
    hospital_number: 1234567890,
    hospital_address: "Belapur, Mumbai, India",
    description: "Ear Infection Consultation",
    time: "2023-09-27T12:15:00.000Z",
    is_emergency: 0,
    status: 1,
    prescription: null,
  },
  {
    a_id: 9,
    patient: 109,
    doctor_name: "Dr. Vikram Joshi",
    doctor_number: 5555555555,
    specialization: "Dentist",
    rating: 4.7,
    hospital_name: "Columbia Asia Hospital Bangalore",
    hospital_number: 9876543210,
    hospital_address: "Whitefield, Bangalore, India",
    description: "Toothache Consultation",
    time: "2023-09-28T16:45:00.000Z",
    is_emergency: 0,
    status: -1,
    prescription: null,
  },
  {
    a_id: 10,
    patient: 110,
    doctor_name: "Dr. Sanjay Malhotra",
    doctor_number: 1234567890,
    specialization: "Psychiatrist",
    rating: 4.8,
    hospital_name: "AIIMS Delhi",
    hospital_number: 9876543210,
    hospital_address: "Ansari Nagar, New Delhi, India",
    description: "Mental Health Consultation",
    time: "2023-09-29T11:30:00.000Z",
    is_emergency: 0,
    status: -1,
    prescription: null,
  },
  {
    a_id: 11,
    patient: 111,
    doctor_name: "Dr. Preeti Khanna",
    doctor_number: 9876543210,
    specialization: "Gastroenterologist",
    rating: 4.5,
    hospital_name: "Fortis Hospital Mumbai",
    hospital_number: 1234567890,
    hospital_address: "Mulund West, Mumbai, India",
    description: "Digestive Problems Consultation",
    time: "2023-09-30T09:00:00.000Z",
    is_emergency: 0,
    status: -1,
    prescription: null,
  },
  {
    a_id: 12,
    patient: 112,
    doctor_name: "Dr. Ananya Desai",
    doctor_number: 5555555555,
    specialization: "Endocrinologist",
    rating: 4.9,
    hospital_name: "Apollo Hospital Chennai",
    hospital_number: 9876543210,
    hospital_address: "Greams Road, Chennai, India",
    description: "Thyroid Consultation",
    time: "2023-10-01T15:45:00.000Z",
    is_emergency: 0,
    status: -1,
    prescription: null,
  },
  {
    a_id: 13,
    patient: 113,
    doctor_name: "Dr. Aryan Kapoor",
    doctor_number: 1234567890,
    specialization: "Nephrologist",
    rating: 4.7,
    hospital_name: "Max Hospital Delhi",
    hospital_number: 9876543210,
    hospital_address: "Saket, New Delhi, India",
    description: "Kidney Function Check",
    time: "2023-10-02T14:00:00.000Z",
    is_emergency: 0,
    status: -1,
    prescription: null,
  },
  {
    a_id: 14,
    patient: 114,
    doctor_name: "Dr. Anjali Sharma",
    doctor_number: 9876543210,
    specialization: "Oncologist",
    rating: 4.6,
    hospital_name: "NIMHANS Bangalore",
    hospital_number: 1234567890,
    hospital_address: "Hosur Road, Bangalore, India",
    description: "Cancer Consultation",
    time: "2023-10-03T12:30:00.000Z",
    is_emergency: 0,
    status: -1,
    prescription: null,
  },
  {
    a_id: 15,
    patient: 115,
    doctor_name: "Dr. Sameer Verma",
    doctor_number: 5555555555,
    specialization: "Dermatologist",
    rating: 4.8,
    hospital_name: "Rainbow Children's Hospital Hyderabad",
    hospital_number: 9876543210,
    hospital_address: "Banjara Hills, Hyderabad, India",
    description: "Skin Allergy Consultation",
    time: "2023-10-04T10:45:00.000Z",
    is_emergency: 0,
    status: -1,
    prescription: null,
  },
  {
    a_id: 16,
    patient: 116,
    doctor_name: "Dr. Priyanka Deshmukh",
    doctor_number: 1234567890,
    specialization: "Ophthalmologist",
    rating: 4.9,
    hospital_name: "Shankar Netralaya Chennai",
    hospital_number: 9876543210,
    hospital_address: "Radhakrishnan Salai, Chennai, India",
    description: "Eye Checkup",
    time: "2023-10-05T15:15:00.000Z",
    is_emergency: 0,
    status: -1,
    prescription: null,
  },
  {
    a_id: 17,
    patient: 117,
    doctor_name: "Dr. Arvind Kapoor",
    doctor_number: 9876543210,
    specialization: "ENT Specialist",
    rating: 4.6,
    hospital_name: "Apollo Hospital Mumbai",
    hospital_number: 1234567890,
    hospital_address: "Belapur, Mumbai, India",
    description: "Ear Pain Consultation",
    time: "2023-10-06T09:30:00.000Z",
    is_emergency: 0,
    status: -1,
    prescription: null,
  },
  {
    a_id: 18,
    patient: 118,
    doctor_name: "Dr. Neha Reddy",
    doctor_number: 5555555555,
    specialization: "Dentist",
    rating: 4.7,
    hospital_name: "Columbia Asia Hospital Bangalore",
    hospital_number: 9876543210,
    hospital_address: "Whitefield, Bangalore, India",
    description: "Tooth Extraction",
    time: "2023-10-07T14:45:00.000Z",
    is_emergency: 0,
    status: -1,
    prescription: null,
  },
  {
    a_id: 19,
    patient: 119,
    doctor_name: "Dr. Sanjeev Khanna",
    doctor_number: 1234567890,
    specialization: "Psychiatrist",
    rating: 4.8,
    hospital_name: "AIIMS Delhi",
    hospital_number: 9876543210,
    hospital_address: "Ansari Nagar, New Delhi, India",
    description: "Mental Health Consultation",
    time: "2023-10-08T11:00:00.000Z",
    is_emergency: 0,
    status: -1,
    prescription: null,
  },
  {
    a_id: 20,
    patient: 120,
    doctor_name: "Dr. Pooja Mehta",
    doctor_number: 9876543210,
    specialization: "Gastroenterologist",
    rating: 4.5,
    hospital_name: "Fortis Hospital Mumbai",
    hospital_number: 1234567890,
    hospital_address: "Mulund West, Mumbai, India",
    description: "Stomach Pain Consultation",
    time: "2023-10-09T16:15:00.000Z",
    is_emergency: 0,
    status: -1,
    prescription: null,
  },
];

export const doctorsList = [
  {
    id: 1,
    name: "Dr. John Doe",
    specialization: "Cardiologist",
    hospital: "XYZ Hospital",
    image: "doctor1.jpg", // You can place the doctor's image in the public folder
  },
  {
    id: 2,
    name: "Dr. Jane Smith",
    specialization: "Pediatrician",
    hospital: "ABC Children's Hospital",
    image: "doctor2.jpg",
  },
  // Add more doctors as needed
];

export const doctorAppointments = [
  {
    a_id: 1,
    patient: 101,
    doctor: 201,
    hospital: 401,
    description: "Routine Health Checkup",
    time: "2023-09-20T10:00:00.000Z",
    is_emergency: 0,
    status: -1,
    prescription: null,
    patient_name: "Rajesh Kumar",
    hospital_name: "Indian General Hospital",
    hospital_address: "789 MG Road, Mumbai, India",
  },
  {
    a_id: 2,
    patient: 102,
    doctor: 201,
    hospital: 402,
    description: "Dental Checkup",
    time: "2023-09-20T14:30:00.000Z",
    is_emergency: 0,
    status: -1,
    prescription: null,
    patient_name: "Priya Sharma",
    hospital_name: "Delhi Dental Clinic",
    hospital_address: "567 Nehru Place, Delhi, India",
  },
  {
    a_id: 3,
    patient: 103,
    doctor: 202,
    hospital: 401,
    description: "Eye Checkup",
    time: "2023-09-21T11:15:00.000Z",
    is_emergency: 0,
    status: 0,
    prescription: null,
    patient_name: "Amit Patel",
    hospital_name: "Indian General Hospital",
    hospital_address: "789 MG Road, Mumbai, India",
  },
  {
    a_id: 4,
    patient: 104,
    doctor: 203,
    hospital: 403,
    description: "Pediatric Consultation",
    time: "2023-09-22T09:45:00.000Z",
    is_emergency: 0,
    status: -1,
    prescription: null,
    patient_name: "Neha Gupta",
    hospital_name: "Chennai Children's Clinic",
    hospital_address: "123 Anna Nagar, Chennai, India",
  },
  {
    a_id: 5,
    patient: 105,
    doctor: 204,
    hospital: 404,
    description: "Dermatology Appointment",
    time: "2023-09-22T15:30:00.000Z",
    is_emergency: 0,
    status: -1,
    prescription: null,
    patient_name: "Vikram Singh",
    hospital_name: "Kolkata Skin Clinic",
    hospital_address: "456 Park Street, Kolkata, India",
  },
  {
    a_id: 6,
    patient: 106,
    doctor: 205,
    hospital: 405,
    description: "Orthopedic Consultation",
    time: "2023-09-23T13:20:00.000Z",
    is_emergency: 0,
    status: -1,
    prescription: null,
    patient_name: "Pooja Verma",
    hospital_name: "Pune Ortho Care",
    hospital_address: "789 Pune Road, Pune, India",
  },
  {
    a_id: 7,
    patient: 107,
    doctor: 206,
    hospital: 406,
    description: "ENT Checkup",
    time: "2023-09-24T10:45:00.000Z",
    is_emergency: 0,
    status: -1,
    prescription: null,
    patient_name: "Rahul Tiwari",
    hospital_name: "Bangalore ENT Clinic",
    hospital_address: "234 MG Road, Bangalore, India",
  },
  {
    a_id: 8,
    patient: 108,
    doctor: 207,
    hospital: 401,
    description: "Cardiology Consultation",
    time: "2023-09-25T14:00:00.000Z",
    is_emergency: 0,
    status: -1,
    prescription: null,
    patient_name: "Anjali Kapoor",
    hospital_name: "Indian General Hospital",
    hospital_address: "789 MG Road, Mumbai, India",
  },
  {
    a_id: 9,
    patient: 109,
    doctor: 208,
    hospital: 407,
    description: "Gastroenterology Appointment",
    time: "2023-09-26T12:30:00.000Z",
    is_emergency: 0,
    status: -1,
    prescription: null,
    patient_name: "Sachin Sharma",
    hospital_name: "Hyderabad Gastro Care",
    hospital_address: "567 Charminar Road, Hyderabad, India",
  },
  {
    a_id: 10,
    patient: 110,
    doctor: 209,
    hospital: 402,
    description: "Dental Cleaning",
    time: "2023-09-27T09:15:00.000Z",
    is_emergency: 0,
    status: -1,
    prescription: null,
    patient_name: "Sneha Singhania",
    hospital_name: "Delhi Dental Clinic",
    hospital_address: "567 Nehru Place, Delhi, India",
  },
  {
    a_id: 11,
    patient: 111,
    doctor: 210,
    hospital: 403,
    description: "Neurology Consultation",
    time: "2023-09-28T16:30:00.000Z",
    is_emergency: 0,
    status: -1,
    prescription: null,
    patient_name: "Arun Verma",
    hospital_name: "Chennai Neuro Clinic",
    hospital_address: "123 Anna Nagar, Chennai, India",
  },
  {
    a_id: 12,
    patient: 112,
    doctor: 211,
    hospital: 404,
    description: "Dermatology Checkup",
    time: "2023-09-29T11:50:00.000Z",
    is_emergency: 0,
    status: -1,
    prescription: null,
    patient_name: "Sara Khan",
    hospital_name: "Kolkata Skin Clinic",
    hospital_address: "456 Park Street, Kolkata, India",
  },
  {
    a_id: 13,
    patient: 113,
    doctor: 212,
    hospital: 405,
    description: "Orthopedic Consultation",
    time: "2023-09-30T15:10:00.000Z",
    is_emergency: 0,
    status: -1,
    prescription: null,
    patient_name: "Rajat Sharma",
    hospital_name: "Pune Ortho Care",
    hospital_address: "789 Pune Road, Pune, India",
  },
  {
    a_id: 14,
    patient: 114,
    doctor: 213,
    hospital: 406,
    description: "ENT Checkup",
    time: "2023-10-01T10:30:00.000Z",
    is_emergency: 0,
    status: -1,
    prescription: null,
    patient_name: "Kavita Gupta",
    hospital_name: "Bangalore ENT Clinic",
    hospital_address: "234 MG Road, Bangalore, India",
  },
  {
    a_id: 15,
    patient: 115,
    doctor: 214,
    hospital: 407,
    description: "Ophthalmology Appointment",
    time: "2023-10-02T13:45:00.000Z",
    is_emergency: 0,
    status: -1,
    prescription: null,
    patient_name: "Alok Yadav",
    hospital_name: "Hyderabad Eye Institute",
    hospital_address: "567 Charminar Road, Hyderabad",
  },
];
